/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "device_discover.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DiscoverRequest, DiscoverRequest, AUTO)


PB_BIND(DiscoverResponse, DiscoverResponse, AUTO)


PB_BIND(DeviceRegisterRequest, DeviceRegisterRequest, AUTO)


PB_BIND(DeviceRegisterResponse, DeviceRegisterResponse, AUTO)


PB_BIND(DeviceConfig, DeviceConfig, AUTO)


PB_BIND(RunRecord, RunRecord, AUTO)


PB_BIND(TemperatureRecord, TemperatureRecord, AUTO)



