/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_TEMPERATURE_NODE_PB_H_INCLUDED
#define PB_TEMPERATURE_NODE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _TemperatureNodeReport {
    pb_callback_t temperature;
    pb_callback_t humidity;
    float battery_vcc;
    uint32_t rec_delta;
} TemperatureNodeReport;


/* Initializer values for message structs */
#define TemperatureNodeReport_init_default       {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define TemperatureNodeReport_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define TemperatureNodeReport_temperature_tag    1
#define TemperatureNodeReport_humidity_tag       2
#define TemperatureNodeReport_battery_vcc_tag    3
#define TemperatureNodeReport_rec_delta_tag      4

/* Struct field encoding specification for nanopb */
#define TemperatureNodeReport_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FLOAT,    temperature,       1) \
X(a, CALLBACK, REPEATED, FLOAT,    humidity,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_vcc,       3) \
X(a, STATIC,   SINGULAR, UINT32,   rec_delta,         4)
#define TemperatureNodeReport_CALLBACK pb_default_field_callback
#define TemperatureNodeReport_DEFAULT NULL

extern const pb_msgdesc_t TemperatureNodeReport_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TemperatureNodeReport_fields &TemperatureNodeReport_msg

/* Maximum encoded size of messages (where known) */
/* TemperatureNodeReport_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
